### ISSUE TITLE
Image toolkit settings are not saved

### ISSUE THREAD

**Issue by korontari** [backdrop-contrib/graphicsmagick#13]
GraphicsMagick toolkit settings are not saved. Also it looks like there are no defaults loaded into the form.
Steps to reproduce:
1. Install and enable GraphicsMagick toolkit module.
2. Go to admin/config/media/image-toolkit and set GraphicsMagick as an image processing toolkit. Save configuration.
3. Try to adjust/input any of the settings for the new toolkit.
4. Press 'Save configuration'.

I am not sure but maybe there should be a submit function that saves the result of image_graphicsmagick_toolkit_settings()? At least all the admin forms I dealt with had a corresponding submit function.

PS: Thank you very much for working on such a needed module (needed for me at least 😃)!

**Comment by avpaderno** [comment]
Thank you for your report!

The submission handler is already provided by Backdrop with [`system_image_toolkit_settings_submit()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.admin.inc/function/system_image_toolkit_settings_submit/1).

The issue is that the module is not correctly retrieving the stored configuration values.
